# Site settings
title: Punya Ruchal
email: info@punya.com.np
description: Punya Ruchal perosnal blog.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://punya.com.np" # the base hostname & protocol for your site
twitter_username: punyaruchal
github_username:  punyaruchal

# Build settings
markdown: kramdown

port: 8080