# Site settings
title: Punya Ruchal - Front-end and Web Developer
email: info@punya.com.np
description: Punya Ruchal perosnal blog.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://punya.com.np" # the base hostname & protocol for your live site
#url: "" # the base hostname & protocol for your local site
encoding:         UTF-8
twitter_username: punyaruchal
github_username:  punyaruchal

# Build settings
markdown: kramdown

#Browser port, e.g. localhosty:8080
port: 8080

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-70913950-1